### ISSUE TITLE
Palette not reverting back to Index 0 (Transparency)

### ISSUE THREAD

**Issue by PurpBatBoi** [saltern/Godot-Shaders#1]
Hi 
im having this issue where i switch to a new palette set, the transparent background gets replaced by the last index color (14)
https://user-images.githubusercontent.com/97393974/197021359-c520cb12-e01b-4d79-b524-c9c4a025ea25.mp4

Here's how my sprite and palette look
![image](https://user-images.githubusercontent.com/97393974/197021967-0480f680-5dc9-43a8-8a6d-1b3794cb95fd.png)
![image](https://user-images.githubusercontent.com/97393974/197022014-b4209634-dacb-428f-8f56-1d33bb86f1b1.png)

**Comment by saltern** [comment]
I just tried the sprite and palette shown in the screenshots in Godot 3.5.1 stable, and they seem to be working fine on my end.

![image](https://user-images.githubusercontent.com/93945502/197027651-a4a118dc-77b5-44f5-8e52-6066ec94ea11.png)

This is Godot 3 MultiPal, right? Have you checked that both the sprite itself and the palette were imported losslessly, with no filtering, etc.? If that doesn't help, could you maybe upload the sprite/palette so I can take a look?

**Comment by PurpBatBoi** [comment]
> I just tried the sprite and palette shown in the screenshots in Godot 3.5.1 stable, and they seem to be working fine on my end.
> 
> ![image](https://user-images.githubusercontent.com/93945502/197027651-a4a118dc-77b5-44f5-8e52-6066ec94ea11.png)
> 
> This is Godot 3 MultiPal, right? Have you checked that both the sprite itself and the palette were imported losslessly, with no filtering, etc.? If that doesn't help, could you maybe upload the sprite/palette so I can take a look?

Sprite Settings
![image](https://user-images.githubusercontent.com/97393974/197029507-97656106-4567-4262-8c3e-0b923264310f.png)


Palette Settings
![image](https://user-images.githubusercontent.com/97393974/197029649-56ee704b-ddc9-461b-aaf8-1c4098113200.png)

![richter](https://user-images.githubusercontent.com/97393974/197029796-5b37ebd7-4857-4758-8848-3c9d24a3e543.png)
![richter_pal](https://user-images.githubusercontent.com/97393974/197029836-ebe162f6-ce04-46bd-aec1-3eae6788853e.png)

Im using Godot v3.5.1.stable.official [6fed1ffa3]
on Windows 10 64-Bit, Intel 3230M, Intel HD4000 iGPU

**Comment by saltern** [comment]
Just confirmed we're on the same version of Godot, checked with your files, and even on the demo project which I can see was open in the video to maybe check if the bundled version of the shader in there was borked for some reason, but I still can't replicate this. I'll keep trying but honestly I'm unsure what to look out for. 😅

**Comment by PurpBatBoi** [comment]
> Just confirmed we're on the same version of Godot, checked with your files, and even on the demo project which I can see was open in the video to maybe check if the bundled version of the shader in there was borked for some reason, but I still can't replicate this. I'll keep trying but honestly I'm unsure what to look out for. 😅

Not borked and idk why it happens, i'll open it on godot on linux to see if this bug persists

edit, still happens on linux too

**Comment by saltern** [comment]
I'm wondering if it might be a hardware rounding error or something of the sort.

**Comment by PurpBatBoi** [comment]
> I'm wondering if it might be a hardware rounding error or something of the sort.

i doubt, since the multi palette on your robot works just as intended

**Comment by PurpBatBoi** [comment]
![image](https://user-images.githubusercontent.com/97393974/197036255-500ec216-ec1d-40fa-b68b-098500dbcb94.png)
huh even if the sprite doesn't follow any of the correct settings, it still display fine

**Comment by saltern** [comment]
What matters the most if lossless compression on import. The shader samples the palette from the center of each pixel for accuracy so that's probably why it still looks fine even if the palette itself is filtered. :)

Does it work fine under Linux? That'd probably rule out the hardware theory.

**Comment by PurpBatBoi** [comment]
> What matters the most if lossless compression on import. The shader samples the palette from the center of each pixel for accuracy so that's probably why it still looks fine even if the palette itself is filtered. :)
> 
> Does it work fine under Linux? That'd probably rule out the hardware theory.

still happens on linux

**Comment by PurpBatBoi** [comment]
> What matters the most if lossless compression on import. The shader samples the palette from the center of each pixel for accuracy so that's probably why it still looks fine even if the palette itself is filtered. :)
> 
> Does it work fine under Linux? That'd probably rule out the hardware theory.

![image](https://user-images.githubusercontent.com/97393974/197039306-6c687643-7a5b-4bac-b914-131bafa76074.png)
even tested with the latest 4.0 beta and still happens, Huh

**Comment by saltern** [comment]
I tried to manually add errors to the shader to see if I can replicate the effect, but I'm getting nowhere. You seem to have done everything exactly right so I don't know if this'll help, but if it's not too much trouble could you maybe upload a project with the issue?

**Comment by PurpBatBoi** [comment]
[AdvPal3Demo.zip](https://github.com/saltern/Godot-Shaders/files/9833333/AdvPal3Demo.zip)
here

**Comment by saltern** [comment]
As I thought, nothing's different. Could you try these two palettes and see what kind of results you get? The first one has the last color in each pal replaced, and the second has an extra transparent column to the right.

![14_replaced](https://user-images.githubusercontent.com/93945502/197041226-17bf690c-1dec-4a1d-9815-487fd6602418.png)
![15_colors](https://user-images.githubusercontent.com/93945502/197041231-ae53ab0b-80ba-4e42-a06b-0e6fa9a477c9.png)

**Comment by PurpBatBoi** [comment]
> As I thought, nothing's different. Could you try these two palettes and see what kind of results you get? The first one has the last color in each pal replaced, and the second has an extra transparent column to the right.
> 
> ![14_replaced](https://user-images.githubusercontent.com/93945502/197041226-17bf690c-1dec-4a1d-9815-487fd6602418.png) ![15_colors](https://user-images.githubusercontent.com/93945502/197041231-ae53ab0b-80ba-4e42-a06b-0e6fa9a477c9.png)

The one with a 2nd extra transparent column worked

**Comment by saltern** [comment]
To be completely honest I'm not totally happy with a hack like that but I don't have much of a way to test for this issue. 😅
When using the first palette, did the background get tinted the same color as the clothes? For example, was the background in the yellow palette yellow or was it blue/green?

**Comment by PurpBatBoi** [comment]
> To be completely honest I'm not totally happy with a hack like that but I don't have much of a way to test for this issue. sweat_smile When using the first palette, did the background get tinted the same color as the clothes? For example, was the background in the yellow palette yellow or was it blue/green?

it was blue and yellow

**Comment by PurpBatBoi** [comment]
![image](https://user-images.githubusercontent.com/97393974/197043423-bc25e870-2353-45d7-8d2b-251d416c167e.png)
so godot is reading the palette like this

**Comment by PurpBatBoi** [comment]
each row of new colors must also have its own transparency color

**Comment by saltern** [comment]
If the background was a different color (for example, blue in the yellow palette, and yellow in the green palette) that means that for some reason, the sample index was being rounded down for color #0. So instead of sampling color #15 (transparency for palette 2), it was doing #14. Strange.

If you change line 57 in the shader, right below the "Multiple palettes" comment, to just this:
`float palAdd = paletteNumber * float(palSize.x);`

Does the shader work fine with your original palette? The one without the extra transparent row.

**Comment by PurpBatBoi** [comment]
> 

Nope didn't work

**Comment by PurpBatBoi** [comment]
![image](https://user-images.githubusercontent.com/97393974/197051955-6dcf748e-6c44-44e0-9cf9-f3b5cc044984.png)
IDK WHAT I DID BUT IT WORKS NOW?
![image](https://user-images.githubusercontent.com/97393974/197052029-fe1db9a4-543c-4862-9c66-603c7b8066dd.png)
I Set my palette to use 16 colors now, i think that fixes it now

**Comment by saltern** [comment]
All this keeps screaming "rounding error" at me, lol. I'll see if this bug happens on a different machine and if there's anything I can do to fix it proper. For the moment I hope you don't mind having to use that extra row. 🙏

Edit: I have managed to reproduce this by opening the project in a different PC.

**Comment by PurpBatBoi** [comment]
> All this keeps screaming "rounding error" at me, lol. I'll see if this bug happens on a different machine and if there's anything I can do to fix it proper. For the moment I hope you don't mind having to use that extra row. pray
> 
> Edit: I have managed to reproduce this by opening the project in a different PC.

ooh

**Comment by saltern** [comment]
I think I have a working fix. I'll be uploading it in a bit, and if it's working, I'll go ahead and close this.

**Comment by saltern** [comment]
Just committed the fix for the Godot 3 version of the shader, if you confirm it's working for you I'll go ahead and fix the Godot 4 version and then close the issue. :D

**Comment by PurpBatBoi** [comment]
> Just committed the fix for the Godot 3 version of the shader, if you confirm it's working for you I'll go ahead and fix the Godot 4 version and then close the issue. :D

thank you!

**Comment by PurpBatBoi** [comment]
btw i recommend fixing the other versions too

**Comment by saltern** [comment]
I did fix the Godot 4 version, and the non-multipal versions don't use the palette selector, so I didn't check them. Do they have this problem as well?

**Comment by PurpBatBoi** [comment]
> 

tbh idk i haven't tested them but since they don't have to switch to other palettes 
they probably don't have the problem

**Comment by saltern** [comment]
I just tested the Godot 3 and 4 versions on the other PC and they seem to be working fine as they are, so I think I can close this and call it fixed. Thanks for reporting this!
