### ISSUE TITLE
Transparent and emissive colors on textures

### ISSUE THREAD

**Issue by Alevam-Inc** [saltern/Godot-Shaders#2]
Would it be possible to create a shader that mimics the fullbright colors used in the original quake, i.e. colors in a palette that are not affected by shadows?

Example:
![image](https://github.com/saltern/Godot-Shaders/assets/50853470/e7af650b-8f0c-4368-b32b-272b417775e1)

**Comment by saltern** [comment]
Closing this as discussed over on YT; for anyone else who might be looking to replicate this effect:

1. Create a second StandardMaterial pass
2. Set its Transparency mode to Alpha, and shading mode to Unshaded
3. Create a version of the base texture containing only the pixels that should be fully lit at all times, and use it as the Albedo texture
